# Generated by Django 2.0.4 on 2018-08-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brewer', models.CharField(max_length=50)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hops', models.CharField(max_length=255)),
                ('ideal_temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('brewery_type', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=14)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('phone', models.CharField(max_length=17)),
                ('website_url', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brewery_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerapp.Beer')),
            ],
        ),
    ]
