# Generated by Django 2.0.4 on 2018-09-04 15:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='id',
            new_name='brewer_api_id',
        ),
        migrations.RenameField(
            model_name='brewery',
            old_name='street',
            new_name='streetAddress',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='hops',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='ideal_temp',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='beer',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_api_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='beer',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='<comment here>'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.IntegerField(blank=True, default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerapp.Brewery'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='brewery_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='latitude',
            field=models.DecimalField(decimal_places=13, default=Decimal('0E-13'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='longitude',
            field=models.DecimalField(decimal_places=13, default=Decimal('0E-13'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='website_url',
            field=models.URLField(),
        ),
    ]
