# Generated by Django 2.0.4 on 2018-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0003_auto_20180919_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beerid', models.CharField(max_length=50)),
                ('beername', models.CharField(max_length=255)),
                ('beerimg', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='address',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='like',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='like',
            name='type',
        ),
    ]
