# Generated by Django 2.0.4 on 2018-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0003_auto_20180904_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='brewer_api_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
    ]
