# Generated by Django 2.0.4 on 2018-09-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerapp', '0004_auto_20180904_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_api_id',
            field=models.IntegerField(default=0),
        ),
    ]
